import PDFDocument from 'pdfkit';

export interface ReceiptData {
  invoiceId: string;
  merchantId: number;
  description: string;
  fiatAmount: number;
  cryptoAmount: number;
  currency: string;
  txid: string;
  paidAt: Date;
  network: string;
}

export async function generateReceipt(data: ReceiptData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const buffers: Buffer[] = [];
    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    doc.rect(0, 0, 595, 120).fill('#1a1a2e');
    doc.fillColor('#ffffff').fontSize(28).font('Helvetica-Bold').text('VERTEXT', 50, 35);
    doc.fillColor('#a0aec0').fontSize(11).font('Helvetica').text('Escrow & Crypto Invoicing Platform', 50, 68);
    doc.roundedRect(440, 35, 105, 32, 8).fill('#0f9b58');
    doc.fillColor('#ffffff').fontSize(11).font('Helvetica-Bold').text('PAYMENT CONFIRMED', 448, 48, { width: 90, align: 'center' });

    doc.fillColor('#1a1a2e').fontSize(22).font('Helvetica-Bold').text('Payment Receipt', 50, 145);
    doc.fillColor('#6c757d').fontSize(10).font('Helvetica').text('Generated: ' + data.paidAt.toUTCString(), 50, 172);
    doc.moveTo(50, 192).lineTo(545, 192).strokeColor('#e2e8f0').lineWidth(1).stroke();

    doc.fillColor('#6c757d').fontSize(9).font('Helvetica').text('INVOICE ID', 50, 210);
    doc.fillColor('#1a1a2e').fontSize(11).font('Helvetica-Bold').text(data.invoiceId, 50, 224, { width: 495 });
    doc.fillColor('#6c757d').fontSize(9).font('Helvetica').text('DESCRIPTION', 50, 255);
    doc.fillColor('#1a1a2e').fontSize(12).font('Helvetica-Bold').text(data.description, 50, 269);
    doc.fillColor('#6c757d').fontSize(9).text('MERCHANT ID', 310, 255);
    doc.fillColor('#1a1a2e').fontSize(12).font('Helvetica-Bold').text(String(data.merchantId), 310, 269);

    doc.rect(50, 310, 495, 120).fill('#f8f9fa').stroke('#e2e8f0');
    doc.fillColor('#1a1a2e').fontSize(13).font('Helvetica-Bold').text('Payment Summary', 70, 325);
    doc.fillColor('#6c757d').fontSize(9).font('Helvetica').text('INVOICE AMOUNT (USD)', 70, 350);
    doc.fillColor('#0f9b58').fontSize(26).font('Helvetica-Bold').text('$' + data.fiatAmount.toFixed(2), 70, 363);
    doc.fillColor('#6c757d').fontSize(9).font('Helvetica').text('CRYPTO PAID', 310, 350);
    doc.fillColor('#1a1a2e').fontSize(16).font('Helvetica-Bold').text(data.cryptoAmount.toFixed(8) + ' ' + data.currency.toUpperCase(), 310, 363);
    doc.fillColor('#6c757d').fontSize(9).font('Helvetica').text('NETWORK', 310, 390);
    doc.fillColor('#1a1a2e').fontSize(11).font('Helvetica-Bold').text(data.network, 310, 403);

    doc.rect(50, 450, 495, 60).fill('#edf2f7').stroke('#e2e8f0');
    doc.fillColor('#6c757d').fontSize(9).font('Helvetica').text('TRANSACTION ID', 70, 465);
    doc.fillColor('#1a1a2e').fontSize(9).font('Helvetica-Bold').text(data.txid || 'Pending', 70, 480, { width: 455 });

    doc.rect(50, 530, 495, 55).fill('#fff3cd').stroke('#ffc107');
    doc.fillColor('#856404').fontSize(9).font('Helvetica-Bold').text('ESCROW PROTECTION ACTIVE', 70, 543);
    doc.fillColor('#856404').fontSize(9).font('Helvetica').text('Funds are held for 24 hours. Use the Report Issue button if you have any problems.', 70, 556, { width: 455 });

    doc.rect(0, 760, 595, 82).fill('#1a1a2e');
    doc.fillColor('#a0aec0').fontSize(8).font('Helvetica').text('Auto-generated by Vertext Escrow Bot. Keep for your records.', 50, 790, { width: 495, align: 'center' });

    doc.end();
  });
}
